# Generated by Django 3.0.6 on 2021-02-19 13:07

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210218_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='image',
            new_name='thumbnail',
        ),
        migrations.AddField(
            model_name='blogs',
            name='image_1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='image_2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='image_3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='image_4',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='image_5',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='short_description',
            field=models.TextField(default='EveryDay'),
            preserve_default=False,
        ),
    ]
