# Generated by Django 3.0.6 on 2021-02-19 14:20

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210219_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSingle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breadcrumb_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='images')),
                ('footer_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='images')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Blog single',
            },
        ),
    ]
